# Generated by Django 4.2.4 on 2023-10-11 00:00

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant')], max_length=10)),
                ('stripe_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('approval_hash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('auto_pay_is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'lease_agreements',
            },
        ),
        migrations.CreateModel(
            name='LeaseTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term', models.IntegerField()),
                ('description', models.TextField()),
                ('late_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_included', models.BooleanField(default=False)),
                ('water_included', models.BooleanField(default=False)),
                ('electric_included', models.BooleanField(default=False)),
                ('repairs_included', models.BooleanField(default=False)),
                ('grace_period', models.IntegerField(default=0)),
                ('lease_cancellation_notice_period', models.IntegerField()),
                ('lease_cancellation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_product_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('stripe_price_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lease_terms',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('street', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, null=True)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'rental_properties',
            },
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('beds', models.PositiveIntegerField()),
                ('baths', models.PositiveIntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lease_term', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.leaseterm')),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalproperty')),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_unit', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rental_units',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('revenue', 'Revenue')], max_length=50)),
                ('description', models.TextField()),
                ('payment_intent_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('payment_method_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rental_property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalproperty')),
                ('rental_unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalunit')),
                ('tenant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_transaction', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='units',
            field=models.ManyToManyField(blank=True, null=True, to='keyflow_backend_app.rentalunit'),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('desired_move_in_date', models.DateField()),
                ('is_archived', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_hash', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('other_occupants', models.BooleanField(default=None)),
                ('pets', models.BooleanField(default=None)),
                ('vehicles', models.BooleanField(default=None)),
                ('convicted', models.BooleanField(default=None)),
                ('bankrupcy_filed', models.BooleanField(default=None)),
                ('evicted', models.BooleanField(default=None)),
                ('employment_history', models.TextField(blank=True, null=True)),
                ('residential_history', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('landlord', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_application_landlord', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_application_tenant', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalunit')),
            ],
            options={
                'db_table': 'rental_applications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('plumbing', 'Plumbling'), ('electrical', 'Electrical'), ('appliance', 'Appliance'), ('structural', 'Structural'), ('other', 'Other')], max_length=35)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('landlord', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rental_property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalproperty')),
                ('rental_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalunit')),
                ('tenant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_maintenance_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_requests',
            },
        ),
        migrations.CreateModel(
            name='LeaseCancellationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lease_agreement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.leaseagreement')),
                ('rental_property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalproperty')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalunit')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lease_cancellation_requests',
            },
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='lease_term',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.leaseterm'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='rental_application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalapplication'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='rental_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalunit'),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccountActivationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_activation_tokens',
            },
        ),
    ]
