# Generated by Django 4.2.4 on 2023-08-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='leaseagreement',
            table='lease_agreements',
        ),
        migrations.AlterModelTable(
            name='maintenancerequest',
            table='maintenance_requests',
        ),
        migrations.AlterModelTable(
            name='rentalproperty',
            table='rental_properties',
        ),
        migrations.AlterModelTable(
            name='rentalunit',
            table='rental_units',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
