# Generated by Django 4.2.4 on 2023-10-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0002_alter_notification_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
