# Generated by Django 4.2.4 on 2023-10-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0003_rentalunit_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalproperty',
            name='units',
        ),
    ]
