# Generated by Django 4.2.4 on 2023-10-17 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0004_remove_rentalproperty_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='rental_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_units', to='keyflow_backend_app.rentalproperty'),
        ),
    ]
