# Generated by Django 4.2.4 on 2023-08-11 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0005_alter_rentalproperty_user_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproperty',
            name='units',
            field=models.ManyToManyField(blank=True, null=True, to='keyflow_backend_app.rentalunit'),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
