# Generated by Django 4.2.4 on 2023-10-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0005_alter_rentalunit_rental_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='rental_application',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalapplication'),
        ),
    ]
