# Generated by Django 4.2.4 on 2023-10-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0006_alter_leaseagreement_rental_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseterm',
            name='additional_charges',
            field=models.TextField(blank=True, null=True),
        ),
    ]
