# Generated by Django 4.2.4 on 2023-08-11 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0006_alter_rentalproperty_units_alter_rentalproperty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
