# Generated by Django 4.2.4 on 2023-10-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0007_leaseterm_additional_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseterm',
            name='template_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
