# Generated by Django 4.2.4 on 2023-11-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0007_alter_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='user_data/'),
        ),
    ]
