# Generated by Django 4.2.4 on 2023-08-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0009_tenantapplication'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tenantapplication',
            table='tenant_applications',
        ),
    ]
