# Generated by Django 4.2.4 on 2023-11-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0010_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_s3_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
