# Generated by Django 4.2.4 on 2023-08-12 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0010_alter_tenantapplication_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasecancellationrequest',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantapplication',
            name='bank_statements',
        ),
        migrations.RemoveField(
            model_name='tenantapplication',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='tenantapplication',
            name='paystubs',
        ),
        migrations.RemoveField(
            model_name='tenantapplication',
            name='references',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasecancellationrequest',
            name='lease_agreement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.leaseagreement'),
        ),
        migrations.AddField(
            model_name='leasecancellationrequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalunit',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantapplication',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='leasecancellationrequest',
            table='lease_cancellation_requests',
        ),
    ]
