# Generated by Django 4.2.4 on 2023-08-13 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0011_remove_leasecancellationrequest_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecancellationrequest',
            name='rental_property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalproperty'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='landlord',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='rental_property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalproperty'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='rental_property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalproperty'),
        ),
        migrations.AlterField(
            model_name='leasecancellationrequest',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalunit'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_maintenance_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
