# Generated by Django 4.2.4 on 2023-11-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0011_alter_uploadedfile_file_s3_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='subfolder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
