# Generated by Django 4.2.4 on 2023-11-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0013_user_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasetemplate',
            name='additional_charges',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
