# Generated by Django 4.2.4 on 2023-08-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0014_rentalproperty_city_rentalproperty_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
