# Generated by Django 4.2.4 on 2023-08-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0015_rentalunit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalunit',
            old_name='price',
            new_name='rent',
        ),
    ]
