# Generated by Django 4.2.4 on 2023-11-24 17:53

from django.db import migrations, models
import keyflow_backend_app.models.uploaded_file


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0015_alter_maintenancerequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(max_length=1000, upload_to=keyflow_backend_app.models.uploaded_file.user_directory_path),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_s3_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
