# Generated by Django 4.2.4 on 2023-08-20 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0016_rename_price_rentalunit_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_unit', to=settings.AUTH_USER_MODEL),
        ),
    ]
