# Generated by Django 4.2.4 on 2023-11-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0017_uploadedfile_file_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_s3_url',
        ),
    ]
