# Generated by Django 4.2.4 on 2023-08-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0018_transaction_type_user_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantApplication',
            new_name='RentalApplication',
        ),
        migrations.AlterModelTable(
            name='rentalapplication',
            table='rental_applications',
        ),
    ]
