# Generated by Django 4.2.4 on 2023-11-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0018_remove_uploadedfile_file_s3_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_s3_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
