# Generated by Django 4.2.4 on 2023-08-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0019_rename_tenantapplication_rentalapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term', models.IntegerField()),
                ('description', models.TextField()),
                ('late_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('secutiry_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_included', models.BooleanField(default=False)),
                ('water_included', models.BooleanField(default=False)),
                ('electric_included', models.BooleanField(default=False)),
                ('repairs_included', models.BooleanField(default=False)),
                ('lease_cancellation_notice_period', models.IntegerField()),
                ('lease_cancellation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'lease_terms',
            },
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='monthly_rent',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='terms',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='document_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='lease_term',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.leaseterm'),
        ),
    ]
