# Generated by Django 4.2.4 on 2023-08-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0020_leaseterm_remove_leaseagreement_monthly_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalapplication',
            name='additional_comments',
        ),
        migrations.RemoveField(
            model_name='rentalunit',
            name='lease_agreement',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='approval_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='approval_hash',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='bankrupcy_filed',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='convicted',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='employment_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='evicted',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='other_occupants',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='pets',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='residential_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='vehicles',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='rentalunit',
            name='least_term',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.leaseterm'),
        ),
    ]
