# Generated by Django 4.2.4 on 2023-08-26 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0021_remove_rentalapplication_additional_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalunit'),
        ),
    ]
