# Generated by Django 4.2.4 on 2023-08-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0022_remove_rentalapplication_user_rentalapplication_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
