# Generated by Django 4.2.4 on 2023-12-01 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0022_message_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leasecancellationrequest',
            old_name='unit',
            new_name='rental_unit',
        ),
        migrations.AddField(
            model_name='leasecancellationrequest',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='leasecancellationrequest',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests_as_tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leasecancellationrequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests_as_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
