# Generated by Django 4.2.4 on 2023-12-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0023_rename_unit_leasecancellationrequest_rental_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecancellationrequest',
            name='reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
