# Generated by Django 4.2.4 on 2023-12-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0024_leasecancellationrequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasecancellationrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='leasecancellationrequest',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
