# Generated by Django 4.2.4 on 2023-12-12 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0025_remove_leasecancellationrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRenewalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateTimeField()),
                ('request_date', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=255)),
                ('lease_agreement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.leaseagreement')),
                ('rental_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalunit')),
                ('tenant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests_as_tenant', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
