# Generated by Django 4.2.4 on 2023-12-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0027_rename_lease_agreement_leaserenewalrequest_current_lease_agreement_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leaserenewalrequest',
            table='lease_renewal_requests',
        ),
    ]
