# Generated by Django 4.2.4 on 2023-12-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0028_alter_leaserenewalrequest_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaserenewalrequest',
            name='renewal_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
