# Generated by Django 4.2.4 on 2023-12-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0029_alter_leaserenewalrequest_renewal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserenewalrequest',
            name='move_in_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
