# Generated by Django 4.2.4 on 2023-08-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0029_alter_rentalapplication_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
