# Generated by Django 4.2.4 on 2023-12-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0031_leaserenewalrequest_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserenewalrequest',
            name='rental_property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalproperty'),
        ),
    ]
