# Generated by Django 4.2.4 on 2023-08-29 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0033_rentalapplication_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='rental_property',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='rental_application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalapplication'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
