# Generated by Django 4.2.4 on 2023-12-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0034_remove_leaserenewalrequest_date_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasetemplate',
            name='lease_renewal_fee',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leasetemplate',
            name='lease_renewal_notice_period',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
