# Generated by Django 4.2.4 on 2023-08-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0035_alter_leaseagreement_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
