# Generated by Django 4.2.4 on 2023-12-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0035_leasetemplate_lease_renewal_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserenewalrequest',
            name='request_term',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
