# Generated by Django 4.2.4 on 2023-08-29 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0036_rentalapplication_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseterm',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
