# Generated by Django 4.2.4 on 2023-12-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0037_remove_leaserenewalrequest_current_lease_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaserenewalrequest',
            name='new_lease_agreement',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='lease_renewal_request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.leaserenewalrequest'),
        ),
    ]
