# Generated by Django 4.2.4 on 2023-08-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0038_rename_secutiry_deposit_leaseterm_security_deposit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalunit',
            old_name='least_term',
            new_name='lease_term',
        ),
    ]
