# Generated by Django 4.2.4 on 2023-12-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0039_notification_resource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='resource_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
