# Generated by Django 4.2.4 on 2023-09-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0039_rename_least_term_rentalunit_lease_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseterm',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_intent_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
