# Generated by Django 4.2.4 on 2023-09-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0040_remove_leaseterm_unit_remove_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseterm',
            name='stripe_price_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaseterm',
            name='stripe_product_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaseterm',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
