# Generated by Django 4.2.4 on 2023-12-26 21:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0041_alter_notification_resource_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'owners',
            },
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='rentalapplication',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_subscription_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant'), ('staff', 'Staff')], max_length=10),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner_tenant', to='keyflow_backend_app.owner')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('privileges', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner_staff', to='keyflow_backend_app.owner')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.owner'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_application_landlord', to='keyflow_backend_app.owner'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='keyflow_backend_app.tenant'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to='keyflow_backend_app.owner'),
        ),
        migrations.AlterField(
            model_name='leasecancellationrequest',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests_as_tenant', to='keyflow_backend_app.tenant'),
        ),
        migrations.AlterField(
            model_name='leasecancellationrequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests_as_user', to='keyflow_backend_app.owner'),
        ),
        migrations.AlterField(
            model_name='leaserenewalrequest',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests_as_tenant', to='keyflow_backend_app.tenant'),
        ),
        migrations.AlterField(
            model_name='leaserenewalrequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests_as_user', to='keyflow_backend_app.owner'),
        ),
        migrations.AlterField(
            model_name='leasetemplate',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.owner'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_maintenance_request', to='keyflow_backend_app.tenant'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_application_tenant', to='keyflow_backend_app.tenant'),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.owner'),
        ),
        migrations.AlterField(
            model_name='rentalunit',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_unit', to='keyflow_backend_app.tenant'),
        ),
        migrations.AlterField(
            model_name='rentalunit',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.owner'),
        ),
    ]
