# Generated by Django 4.2.4 on 2023-09-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0041_leaseterm_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalunit',
            name='rent',
        ),
    ]
