# Generated by Django 4.2.4 on 2023-12-27 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0042_owner_remove_maintenancerequest_landlord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaseagreement',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='leasecancellationrequest',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='leaserenewalrequest',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='leasetemplate',
            old_name='user',
            new_name='owner',
        ),
        # migrations.RenameField(
        #     model_name='maintenancerequest',
        #     old_name='user',
        #     new_name='owner',
        # ),
        migrations.RenameField(
            model_name='rentalapplication',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='rentalproperty',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='rentalunit',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
