# Generated by Django 4.2.4 on 2023-09-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0042_remove_rentalunit_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproperty',
            name='zip_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
