# Generated by Django 4.2.4 on 2023-09-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0045_rename_resolved_maintenancerequest_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
