# Generated by Django 4.2.4 on 2023-12-29 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0046_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rental_property',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalproperty'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rental_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalunit'),
        ),
    ]
