# Generated by Django 4.2.4 on 2023-09-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0046_leaseagreement_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='type',
            field=models.CharField(choices=[('plumbing', 'Plumbling'), ('electrical', 'Electrical'), ('structural', 'Structural'), ('other', 'Other')], default='other', max_length=35),
        ),
    ]
