# Generated by Django 4.2.4 on 2024-01-07 00:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0047_alter_transaction_rental_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('security_deposit', 'Security Deposit'), ('rent_payment', 'Rent Payment'), ('late_fee', 'Late Fee'), ('pet_fee', 'Pet Fee'), ('lease_renewal_fee', 'Lease Renewal Fee'), ('lease_cancellation_fee', 'Lease Cancellation Fee'), ('maintenance_fee', 'Maintenance Fee'), ('vendor_payment', 'Vendor Payment'), ('expense', 'Expense'), ('revenue', 'Revenue')], max_length=50),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.owner')),
            ],
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.portfolio'),
        ),
    ]
