# Generated by Django 4.2.4 on 2023-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0047_maintenancerequest_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalproperty',
            old_name='address',
            new_name='street',
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='type',
            field=models.CharField(choices=[('plumbing', 'Plumbling'), ('electrical', 'Electrical'), ('appliance', 'Appliance'), ('structural', 'Structural'), ('other', 'Other')], default='other', max_length=35),
        ),
    ]
