# Generated by Django 4.2.4 on 2023-09-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0048_rename_address_rentalproperty_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='type',
            field=models.CharField(choices=[('plumbing', 'Plumbling'), ('electrical', 'Electrical'), ('appliance', 'Appliance'), ('structural', 'Structural'), ('other', 'Other')], max_length=35),
        ),
    ]
