# Generated by Django 4.2.4 on 2023-09-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0049_alter_maintenancerequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseterm',
            name='grace_period',
            field=models.IntegerField(default=0),
        ),
    ]
