# Generated by Django 4.2.4 on 2023-09-15 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0050_leaseterm_grace_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.RemoveField(
            model_name='leaseterm',
            name='stripe_subscription_id',
        ),
    ]
