# Generated by Django 4.2.4 on 2023-09-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0052_accountactivationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='auto_pay_is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
