# Generated by Django 4.2.4 on 2024-01-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0053_leasetemplate_rent_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproperty',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
