# Generated by Django 4.2.4 on 2023-09-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0053_leaseagreement_auto_pay_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
