# Generated by Django 4.2.4 on 2024-01-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0056_leaseagreement_document_file_rentalunit_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='preferences',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
