# Generated by Django 4.2.4 on 2024-01-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0057_alter_rentalunit_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='template_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
