# Generated by Django 4.2.4 on 2024-01-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0059_rentalunit_additional_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='lease_document_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_units', to='keyflow_backend_app.uploadedfile'),
        ),
    ]
