# Generated by Django 4.2.4 on 2024-01-18 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0061_rename_lease_document_file_rentalunit_signed_lease_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='document_file',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='signed_lease_document_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_agreements', to='keyflow_backend_app.uploadedfile'),
        ),
    ]
