# Generated by Django 4.2.4 on 2024-01-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0062_remove_leaseagreement_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='signed_lease_document_metadata',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='rentalunit',
            name='signed_lease_document_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rental_units', to='keyflow_backend_app.uploadedfile'),
        ),
    ]
