# Generated by Django 4.2.4 on 2024-01-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0064_alter_rentalunit_signed_lease_document_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalunit',
            old_name='preferences',
            new_name='lease_terms',
        ),
    ]
