# Generated by Django 4.2.4 on 2024-01-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0065_rename_preferences_rentalunit_lease_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='is_tenant_invite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
