# Generated by Django 4.2.4 on 2024-01-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0066_leaseagreement_is_tenant_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='tenant_invite',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.tenantinvite'),
        ),
    ]
