# Generated by Django 4.2.4 on 2024-01-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0067_leaseagreement_tenant_invite'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolio',
            table='portfolios',
        ),
    ]
