# Generated by Django 4.2.4 on 2024-02-01 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0069_billingentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingentry',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='billing_entries', to='keyflow_backend_app.owner'),
        ),
    ]
