# Generated by Django 4.2.4 on 2024-02-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0070_alter_billingentry_owner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billingentry',
            table='billing_entries',
        ),
    ]
