# Generated by Django 4.2.4 on 2024-02-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0072_transaction_billing_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingentry',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
