# Generated by Django 4.2.4 on 2024-02-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0073_billingentry_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingentry',
            name='rental_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_entries', to='keyflow_backend_app.rentalunit'),
        ),
    ]
