# Generated by Django 4.2.4 on 2024-02-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0074_billingentry_rental_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
