# Generated by Django 4.2.4 on 2024-04-04 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0077_leaserenewalrequest_rent_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_request_events', to='keyflow_backend_app.maintenancerequest')),
            ],
            options={
                'db_table': 'maintenance_request_events',
            },
        ),
    ]
