# Generated by Django 4.2.4 on 2024-04-24 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0084_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
