# Generated by Django 4.2.4 on 2024-04-24 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0085_announcement_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='delivery_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
