# Generated by Django 4.2.4 on 2024-04-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0087_announcement_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='rental_property',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='rental_unit',
        ),
        migrations.AddField(
            model_name='announcement',
            name='target',
            field=models.TextField(default=None),
        ),
    ]
