# Generated by Django 4.2.4 on 2024-04-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0089_portfolio_preferences_rentalproperty_preference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalproperty',
            old_name='preference',
            new_name='preferences',
        ),
    ]
