# Generated by Django 4.2.4 on 2024-05-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0090_rename_preference_rentalproperty_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='stripe_account_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
