# Generated by Django 4.2.4 on 2024-05-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0090_rename_preference_rentalproperty_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='keyflow_backend_app.owner'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_application_owner', to='keyflow_backend_app.owner'),
        ),
    ]
