# Generated by Django 4.2.4 on 2024-05-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0091_alter_leaseagreement_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='lease_terms',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
