# Generated by Django 4.2.4 on 2024-05-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0092_alter_rentalunit_lease_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='lease_terms',
            field=models.TextField(blank=True, default='\n[\n    {\n        "type": "unit_preferences",\n        "hidden": false,\n        "label": "Accept Rental Applications",\n        "name": "accept_rental_applications",\n        "inputType": "switch",\n        "value": true,\n        "description": "Indicates if the owner is accepting rental applications for this unit"\n    },\n    {\n        "type": "unit_preferences",\n        "hidden": false,\n        "label": "Acccept Lease Renewals",\n        "name": "accept_lease_renewals",\n        "inputType": "switch",\n        "value": true,\n        "description": "Indicates if the owner is accepting lease renewals for this unit"\n    },\n    {\n        "type": "unit_preferences",\n        "hidden": false,\n        "label": "Accept Lease Cancellations",\n        "name": "accept_lease_cancellations",\n        "inputType": "switch",\n        "value": true,\n        "description": "Indicates if the owner is accepting lease cancellations for this unit"\n    }\n]\n', null=True),
        ),
    ]
