# Generated by Django 4.2.4 on 2024-05-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0093_alter_rentalunit_lease_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='lease_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='keyflow_backend_app.leasetemplate'),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='lease_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_properties', to='keyflow_backend_app.leasetemplate'),
        ),
        migrations.AlterField(
            model_name='rentalunit',
            name='lease_terms',
            field=models.TextField(blank=True, default='\n[\n    {\n        "name": "rent",\n        "label": "Rent",\n        "value": 1500,\n        "inputType": "number",\n        "description": "How much you are going to charge for rent per period",\n        "type": "lease"\n    },\n    {\n        "name": "rent_frequency",\n        "label": "Rent Frequency",\n        "inputType": "select",\n        "options": [\n            {\n                "value": "day",\n                "label": "Daily"\n            },\n            {\n                "value": "month",\n                "label": "Monthly"\n            },\n            {\n                "value": "week",\n                "label": "Weekly"\n            },\n            {\n                "value": "year",\n                "label": "Yearly"\n            }\n        ],\n        "value": "month",\n        "description": "How often you are going to charge rent. This can be daily, monthly, weekly, or yearly",\n        "type": "lease"\n    },\n    {\n        "name": "term",\n        "label": "Term",\n        "inputType": "number",\n        "value": 12,\n        "description": "How long the lease is for in the selected rent frequency",\n        "type": "lease"\n    },\n    {\n        "name": "late_fee",\n        "label": "Late Fee",\n        "inputType": "number",\n        "value": 100,\n        "description": "How much you will charge for late rent payments",\n        "type": "lease"\n    },\n    {\n        "name": "security_deposit",\n        "label": "Security Deposit",\n        "inputType": "number",\n        "value": 100,\n        "description": "How much the tenant will pay for a security deposit. This will be returned to them at the end of the lease if all conditions are met",\n        "type": "lease"\n    },\n    {\n        "name": "gas_included",\n        "label": "Include Gas Bill In Rent",\n        "inputType": "switch",\n        "value": true,\n        "description": "Indicates if gas bill is included in the rent",\n        "type": "lease"\n    },\n    {\n        "name": "electricity_included",\n        "label": "Include Electricity Bill In Rent",\n        "inputType": "switch",\n        "value": true,\n        "description": "Indicates if electricity bill is included in the rent",\n        "type": "lease"\n    },\n    {\n        "name": "water_included",\n        "label": "Include Water Bill In Rent",\n        "inputType": "switch",\n        "value": true,\n        "description": "Indicates if water bill is included in the rent",\n        "type": "lease"\n    },\n    {\n        "name": "repairs_included",\n        "label": "Include Repairs In Rent",\n        "inputType": "switch",\n        "value": true,\n        "description": "Indicates if repairs are included in the rent. If not, the tenant will be responsible for all repair bills",\n        "type": "lease"\n    },\n    {\n        "name": "grace_period",\n        "label": "Grace Period",\n        "inputType": "number",\n        "value": 0,\n        "description": "How many days before the first rent payment is due",\n        "type": "lease"\n    },\n    {\n        "name": "lease_cancellation_notice_period",\n        "label": "Lease Cancellation Notice Period",\n        "inputType": "number",\n        "value": 0,\n        "description": "How many months a tenant must wait before the end of the lease to cancel the lease",\n        "type": "lease"\n    },\n    {\n        "name": "lease_cancellation_fee",\n        "label": "Lease Cancellation Fee",\n        "inputType": "number",\n        "value": 0,\n        "description": "How much the tenant must pay to cancel the lease before the end of the lease",\n        "type": "lease"\n    },\n    {\n        "name": "lease_renewal_notice_period",\n        "label": "Lease Renewal Notice Period",\n        "inputType": "number",\n        "value": 0,\n        "description": "How many months before the end of the lease the tenant must notify the owner of their intent to renew the lease",\n        "type": "lease"\n    },\n    {\n        "name": "lease_renewal_fee",\n        "label": "Lease Renewal Fee",\n        "inputType": "number",\n        "value": 0,\n        "description": "How much the tenant must pay to renew the lease",\n        "type": "lease"\n    }\n]\n', null=True),
        ),
    ]
