# Generated by Django 4.2.4 on 2024-05-08 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0096_alter_staff_privileges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default='incomplete', max_length=100, null=True)),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('completed_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.owner')),
                ('staff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_task', to='keyflow_backend_app.staff')),
            ],
        ),
    ]
