# Generated by Django 4.2.4 on 2024-06-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0098_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='auto_renew_is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='auto_pay_is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
