# Generated by Django 4.2.4 on 2024-06-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0099_leaseagreement_auto_renew_is_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='auto_renew_is_enabled',
        ),
        migrations.AddField(
            model_name='tenant',
            name='auto_renew_lease_is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
