# Generated by Django 4.2.4 on 2024-06-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0100_remove_leaseagreement_auto_renew_is_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='auto_renew_lease_is_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
