# Generated by Django 4.2.4 on 2024-06-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0104_tenantinvite_last_sent_at_alter_owner_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinvite',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantinvite',
            name='rental_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.rentalunit', unique=True),
        ),
    ]
