# Generated by Django 4.2.4 on 2024-06-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0104_tenantinvite_last_sent_at_alter_owner_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinvite',
            name='last_sent_at',
            field=models.DateTimeField(default=None),
        ),
    ]
