# Generated by Django 4.2.4 on 2024-06-28 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0105_alter_tenantinvite_last_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinvite',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
