# Generated by Django 4.2.4 on 2024-07-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0105_alter_tenantinvite_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinvite',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
