# Generated by Django 4.2.4 on 2024-07-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0106_alter_tenantinvite_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='auto_pay_is_enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
