# Generated by Django 4.2.4 on 2024-08-04 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0106_alter_tenantinvite_last_sent_at'),
        ('keyflow_backend_app', '0108_alter_rentalunit_lease_terms'),
    ]

    operations = [
    ]
