# Generated by Django 4.2.14 on 2024-08-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0109_merge_20240804_0020'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='maintenancerequest',
        #     name='user',
        # ),
        migrations.RemoveField(
            model_name='rentalapplication',
            name='user',
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='keyflow_backend_app.owner'),
        ),
    ]
