# Generated by Django 4.2.14 on 2024-10-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0110_remove_maintenancerequest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='lease_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaserenewalrequest',
            name='rent_frequency',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
