# Generated by Django 4.2.14 on 2024-10-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0111_leaseagreement_lease_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='lease_terms',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='lease_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='rent_frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
