# Generated by Django 4.2.14 on 2024-10-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyflow_backend_app', '0112_remove_leaseagreement_lease_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='lease_duration',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='rent_frequency',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='lease_terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
