# Generated by Django 4.2.17 on 2025-07-22 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField()),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expiring_token', to='authtoken.token')),
            ],
            options={
                'db_table': 'expiring_tokens',
            },
        ),
    ]
